---
name: CICD
on:
  workflow_dispatch: 
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from Github"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build the app
        run: echo "building the app"
  test:  
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo " testing the container "
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
