# packages or issues and velnerabilities scan
# pip audit

name: Dependency Scan

on:
  workflow_call:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: pip audit dependency scan
        run: pip install pip-audit

      - name: pip audit dependency
        run: pip-audit -r requirements.txt
