#this will deploy the server to the server machine using ssh and scp

name: Deploy Server

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ssh to prod server & create app folder
        uses: appleboy/ssh-action@v1.0.3 # Check the GitHub Marketplace for the latest version
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying server..."
            mkdir -p devops
            sudo apt-get update
            sudo apt-get install docker.io -y
            sudo apt-get install docker-compose -y
            sudo apt-get update
            sudo usermod -aG docker $USER && newgrp docker
            # Add your deployment commands here, for example:

      - name: copy the docker compose
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: ~/devops

      - name: ssh to prod server & run the app
        uses: appleboy/ssh-action@v1.0.3 # Check the GitHub Marketplace for the latest version
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "running the app..."

            export DOCKERHUB_USERNAME=${{ vars.DOCKER_USERNAME }}
            export DOCKERHUB_TAG=${{ github.sha }}
            echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{vars.DOCKER_USERNAME}} --password-stdin
            cd ~/devops 
            sudo docker compose down && docker compose up -d --build --force-recreate --pull always
