---
name: Hello

on:
  push:
    branches: [main]
  
jobs:
  greet:
  
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo " hello $USER "
        
      - name: say hello to user
        run: echo " Hello pramod i am runner "

  details:

    runs-on: ubuntu-latest
    steps:
      - name: version of python, docker, etc
        run: docker --version && python --version

