# APT KEYS, SENSITIVE DATA, CREDENTIALS
#GitLeaks

name: Secrets Scan

on:
  workflow_call:

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate scanning

      - name: Run GitLeaks Scaner
        uses: actions/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
